# Makefile for my renderer library PaCaLib
# This is the opsys-independent Interface
#

NAME                 =  PaCaLib_Base
VERS_MAJOR           =  0
VERS_MINOR           =  1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export SRCDIR        =  .

include $(SCRIPTDIR)/makelib

